[tool.poetry]
name = "visprompt"
version = "0.1.0"
description = ""
authors = ["mschnei"]
packages = [ {include = "visprompt"} ]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
opencv-contrib-python-headless = "*"
click = "*"
numpy = "*"
boto3 = "*"
imageio = "*"
timm = "^0.9.5"
torch = "^2.0.1"
torchvision = "^0.15.2"
fairscale = "^0.4.13"
pyside6 = "^6.5.2"
pip = "^23.2.1"

[tool.poetry.dev-dependencies]
black = "*"
isort= "*"
pre-commit = "*"
pytest = "*"
pytest-black = "*"
bumpversion = "*"
ipykernel = "*"

[tool.poetry.scripts]
print_shape = "visprompt.scripts.print_shape:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
