name: Install dependencies, lint, and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #              install libegl1
      #----------------------------------------------
      - name: Install libegl1
        run: sudo apt-get install -y libegl1
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      #----------------------------------------------
      #           install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install project
        run: poetry install --no-interaction
      #----------------------------------------------
      #              run linting
      #----------------------------------------------
      - name: Lint with isort, black and flake8
        run: |
          poetry run isort visprompt
          poetry run isort tests
          poetry run black visprompt
          poetry run black tests
          poetry run flake8 visprompt
          poetry run flake8 tests
        continue-on-error: true
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Test with pytest
        run: |
          poetry run coverage erase
          poetry run coverage run -a --source=./visprompt --branch -m pytest -s -v --black --isort tests --junit-xml unit_results.xml
          poetry run coverage report
          poetry run coverage xml
